### ISSUE TITLE
code (master branch) is failing during connection

### ISSUE THREAD

**Issue by manzarul** [SolaceSamples/solace-samples-python#17]
Trying to connect with solace pubsub using "tcps" protocol and getting error as below:
 Host is passed as  : "tcps://..solace.cloud:55443"

"2021-06-08 05:46:19,354 [ERROR] solace.messaging.core: [_solace_session.py:602]  [[SERVICE: 0x23bb3d5d988] - [APP ID: app_5ad79947-779e-4da1-896d-7586aa5a3998]] SOLCLIENT_SUBCODE_FAILED_LOADING_TRUSTSTORE
2021-06-08 05:46:19,368 [ERROR] solace.messaging.core: [_solace_session.py:604]  [[SERVICE: 0x23bb3d5d988] - [APP ID: app_5ad79947-779e-4da1-896d-7586aa5a3998]] SESSION CREATION UNSUCCESSFUL. Failed to load trust store.
Traceback (most recent call last):
  File "hello_world_pubsub.py", line 58, in <module>
    .with_reconnection_retry_strategy(RetryStrategy.parametrized_retry(20,3))\
  File "C:\Users\mahaq\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\solace\messaging\messaging_service.py", line 936, in build
    return _BasicMessagingService(config=self._stored_config, application_id=application_id)
  File "C:\Users\mahaq\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\solace\messaging\messaging_service.py", line 482, in __init__
    self._api.create_session(self._config)  # create the session as part of Messaging Service build process
  File "C:\Users\mahaq\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\solace\messaging\core\_solace_session.py", line 605, in create_session
    raise PubSubPlusCoreClientError(message=FAILED_TO_LOAD_TRUST_STORE, sub_code=info_sub_code)
solace.messaging.errors.pubsubplus_client_error.PubSubPlusCoreClientError: SESSION CREATION UNSUCCESSFUL. Failed to load trust store."

**Comment by TamimiGitHub** [comment]
Hey @manzarul ! Have you tried to set the trust store in the broker configuration parameter before connecting to the broker? You can do so as follows

```
broker_props = {
    "solace.messaging.transport.host": os.environ.get('SOLACE_HOST') or "localhost",
    "solace.messaging.service.vpn-name": os.environ.get('SOLACE_VPN') or "default",
    "solace.messaging.authentication.scheme.basic.username": os.environ.get('SOLACE_USERNAME') or "default",
    "solace.messaging.authentication.scheme.basic.password": os.environ.get('SOLACE_PASSWORD') or "default",
    "solace.messaging.tls.trust-store-path": "<path_to_pem_file>"
    }
```

You can download the pem file from your broker from the connect tab, then click on the Solace Messaging menu. Under the Trust Store, download the pem fie. 

Let me know if this is helpful and works for you

**Comment by mhaque07** [comment]
I tried to ignore that pem certificate file and post that change able to consume data from solace queue.
Here is small code change for same:
in import section add: 
 *  from solace.messaging.config.transport_security_strategy import TLS
in code : 
   `
 broker_props = {
    "solace.messaging.transport.host": os.environ.get('SOLACE_HOST') or "localhost",
    "solace.messaging.service.vpn-name": os.environ.get('SOLACE_VPN') or "default",
    "solace.messaging.authentication.scheme.basic.username": os.environ.get('SOLACE_USERNAME') or "default",
    "solace.messaging.authentication.scheme.basic.password": os.environ.get('SOLACE_PASSWORD') or "default"
    }

transport_security = TLS.create().without_certificate_validation()
messaging_service = MessagingService.builder().from_properties(broker_props)\
                    .with_transport_security_strategy(transport_security) \
                    .with_reconnection_retry_strategy(RetryStrategy.parametrized_retry(20,3))\
                    .build()`

**Comment by TamimiGitHub** [comment]
Hey @mhaque07 - thanks for this alternative approach! You can indeed instead import the TLS module from the API. You can check out more details on this example on https://www.solace.dev/ and if you scroll down to the Python category and choose the secured SMG under the "Connect to Service" tab. 

@manzarul let me know if either recommendations work for you.
