### ISSUE TITLE
solbroker_properties.json - might need update?

### ISSUE THREAD

**Issue by ghost** [SolaceSamples/solace-samples-python#24]
Does solbroker_properties.json and/or its reader need to be updated?

I found I had to add two lines to solbrokerProperties to make the sample work:

    "solace.messaging.authentication.basic.username": "default",
    "solace.messaging.authentication.basic.password": "default",

(these are copies of 

    "solace.messaging.authentication.scheme.basic.username": "default",
    "solace.messaging.authentication.scheme.basic.password": "default"

but without ".scheme" in the keys).

I also found I could not just change those lines because the sample code objected (the connection worked but there were warnings).  I had to add new lines with the new hierarchy.

**Comment by TamimiGitHub** [comment]
Fixed in https://github.com/SolaceSamples/solace-samples-python/commit/8e06755307448345afa7e2d69ac98fd367b400f1 

Thanks for the catch!
