### ISSUE TITLE
Examples contain pickling

### ISSUE THREAD

**Issue by saabeilin** [SolaceSamples/solace-samples-python#26]
https://github.com/SolaceSamples/solace-samples-python/search?q=pickle

Pickling is considered a bad practice and should not be used, especially across the wire.

Moreover, it is python-specific, while all message exchange systems promote language-agnostic solutions.

**Comment by TamimiGitHub** [comment]
Hey @saabeilin - thanks for raising this and I see your concern. I want to highlight that this is just a sample on how to use the API. The Solace PubSub+ Messaging API for Python does NOT use pickling, and infact we dont do any payload manipulation on the API/Broker level. This sample is just to show that you can use whatever process/framework you want to (de)serialize your payload. 

The messaging component of all Solace APIs is language agnostic, so in this case using pickling is an example on how applications could approach object marshalling techniques. 

Curious to know - are you using the Solace PubSub+ Messaging API for Python? And what is your use-case?

**Comment by TamimiGitHub** [comment]
Closing for stale activity
