### ISSUE TITLE
Improvement for Python API

### ISSUE THREAD

**Issue by solace-zahratabar** [SolaceSamples/solace-samples-python#38]
The python API sample contained a publish in async way  not waiting for the callback. Without waiting and going on you would not recognize an error on publish and message would get lost.

**Comment by TamimiGitHub** [comment]
Note that errors on publish are only a persistent message publisher and caught in the `MessagePublishReceiptListener`. So if errors happen for a particular published message it should be handled in the publish receipt 

See: https://github.com/SolaceSamples/solace-samples-python/blob/main/patterns/guaranteed_publisher.py#L35-L46

And as per the documentation of the `PersistentMessagePublisher`, there are two methods for publishing: 
- publish: Sends and outbound message to the given destination
- publish_await_acknowledgement: Sends a persistent message, blocking until publish acknowledgement is received or timeout occurs

so if a use-case requires a thread block until an ack is received then a `publish_await_acknowledgement` should be used. 

Note that these samples are meant to show best practices for using the API as a starting grounds but are not meant to be "used as is in production or enterprise environments". Hence, I will close this issue unless there are any further followups on the sample code

**Comment by Mrc0113** [comment]
Hey @TamimiGitHub are you saying that since we are using `publish` (and not the await_ack option) this is the callback? 
https://github.com/SolaceSamples/solace-samples-python/blob/344be1962071422ff534eda48a931abc6f459267/patterns/guaranteed_publisher.py#L43 or is there another callback that we are missing?

**Comment by TamimiGitHub** [comment]
Hey @ZahraTabar, as @Mrc0113 mentioned, the `on_publish_receipt` call back in the `MessageReceiptListener` class handles any errors. Check out what is available in the publish receipt over here in the docs https://docs.solace.com/API-Developer-Online-Ref-Documentation/python/source/rst/solace.messaging.publisher.html#solace.messaging.publisher.persistent_message_publisher.PublishReceipt. You can retrieve exceptions and further context on the message that could be exposed. 

Let me know if this helps with clearing things out!

**Comment by Mrc0113** [comment]
Closing this since there was no follow up.
