### ISSUE TITLE
[Feature]: requesting client certificate script having ssl certificate loading issue

### ISSUE THREAD

**Issue by sowjanya1117** [SolaceSamples/solace-samples-python#47]
### Feature Description

i'm trying to run the patterns publisher code when i run the script with username and password it's publishing the messages now i need some guidence to run the script without using uasername and password use client certificate 

### Use Case

i'm trying to run the patterns publisher code when i run the script with username and password it's publishing the messages now i need some guidence to run the script without using uasername and password use client certificate 
i'm facing uses like solace.messaging is not found these kind of errors i'm getting

**Comment by Mrc0113** [comment]
Hi @sowjanya1117, 

Please see this example of how to add client certification authentication: https://github.com/SolaceSamples/solace-samples-python/blob/5a7f4a83656040e01897e22a8f3a412809d26859/howtos/how_to_configure_authentication.py#L38-L71

Hope that helps!

**Comment by sowjanya1117** [comment]
@Mrc0113 ,thanks for your response i tried that way but i'm facing the below error. "solace.messaging.errors.pubsubplus_client_error.PubSubPlusCoreClientError: SESSION CREATION UNSUCCESSFUL. Failed to load trust store"
1)i'm using the macbook and my ceryificates or in keychain access

**Comment by Mrc0113** [comment]
HI @sowjanya1117, 

Question: Are you using a local broker or Cloud? 

Also when configuring your connection can you check a few things: 
1. Ensure that the user running the app has access to the directory and the certificate itself
2. Ensure you're using "tcps" in the URL to connect & the secure port (usually 55443) 

If you have access to solace support I'd recommend opening a ticket and linking them this issue as they'll probably be quicker to respond :)
